version: '3.8'

services:
  whatsapp-bot:
    image: your-dockerhub-username/whatsapp-bot:latest
    container_name: whatsapp-bot
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - JWT_AUTH_CLIENTS=[{"clientId":"client_id1","clientSecret":"client_secret1","expiresIn":"1h"}]
      - WHATSAPP_CLIENT_STORE_AWS_S3_REGION=eu-west-1
      - WHATSAPP_CLIENT_STORE_AWS_S3_BUCKET=my-bucket
      - WHATSAPP_CLIENT_STORE_AWS_S3_KEY=my-key
      - WHATSAPP_CLIENT_STORE_AWS_S3_SECRET_ACCESS_KEY=my-secret
      - WHATSAPP_CLIENT_STORE_AWS_S3_STORE_PATH=/
    volumes:
      - whatsapp-data:/app/data

volumes:
  whatsapp-data:
